version: '3'

services:
  phonebook-mysql:
    container_name: phonebook-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always

  phonebook-app:
    container_name: phonebook-app
    build:
      context: .
      dockerfile: Dockerfile-app
    depends_on:
      - phonebook-mysql
    ports:
      - "5000:5000"
    restart: always

  prometheus:
    image: prom/prometheus:v2.33.0
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:8.3.4
    ports:
      - 3000:3000
